import os

from talon.voice import Word, Context, Key, Rep, RepPhrase, Str, press
from talon import ctrl, clip
from talon_init import TALON_HOME, TALON_PLUGINS, TALON_USER

ctx = Context("input")

ctx.keymap(
    {
        "tarpy": [Key("tab"), Key("tab")],
        "trough": Key("alt-backspace"),
        "slap": [Key("cmd-right enter")],
        "sky shock": Key("shift-enter"),
        "question [mark]": "?",
        "tilde": "~",
        "(bang | exclamation point)": "!",
        "dollar [sign]": "$",
        "downscore": "_",
        "colon": ":",
        "(brace | left brace)": "{",
        "(rbrace | are brace | right brace)": "}",
        "(angle | left angle | less than)": "<",
        "(rangle | are angle | right angle | greater than)": ">",
        "(star | asterisk)": "*",
        "(pound [sign] | hash [sign] | octo | number sign)": "#",
        "percent [sign]": "%",
        "caret": "^",
        "at sign": "@",
        "(and sign | ampersand | amper)": "&",
        "pipe": "|",
        "(dubquote | double quote)": '"',
        "triple quote": "'''",
        "ricky": Key("ctrl-e"),
        "lefty": Key("ctrl-a"),
        "olly | ali": Key("cmd-a"),
        "(dot dot | dotdot)": "..",
        "(dot dot dot | dotdotdot)": "...",
        "cd talon home": "cd {}".format(TALON_HOME),
        "cd talon user": "cd {}".format(TALON_USER),
        "cd talon plugins": "cd {}".format(TALON_PLUGINS),
        "run make (durr | dear)": "mkdir ",
        "run get": "git ",
        "run get (R M | remove)": "git rm ",
        "run get add": "git add ",
        "run get bisect": "git bisect ",
        "run get branch": "git branch ",
        "run get checkout": "git checkout ",
        "run get clone": "git clone ",
        "run get commit": "git commit ",
        "run get diff": "git diff ",
        "run get fetch": "git fetch ",
        "run get grep": "git grep ",
        "run get in it": "git init ",
        "run get log": "git log ",
        "run get merge": "git merge ",
        "run get move": "git mv ",
        "run get pull": "git pull ",
        "run get push": "git push ",
        "run get rebase": "git rebase ",
        "run get reset": "git reset ",
        "run get show": "git show ",
        "run get status": "git status ",
        "run get tag": "git tag ",
        "run (them | vim)": "vim ",
        "run L S": "ls\n",
        "dot pie": ".py",
        "run make": "make\n",
        "run jobs": "jobs\n",
        "const": "const ",
        "static": "static ",
        "tip pent": "int ",
        "tip char": "char ",
        "tip byte": "byte ",
        "tip pent 64": "int64_t ",
        "tip you went 64": "uint64_t ",
        "tip pent 32": "int32_t ",
        "tip you went 32": "uint32_t ",
        "tip pent 16": "int16_t ",
        "tip you went 16": "uint16_t ",
        "tip pent 8": "int8_t ",
        "tip you went 8": "uint8_t ",
        "tip size": "size_t",
        "tip float": "float ",
        "tip double": "double ",
        "args": ["()", Key("left")],
        "index": ["[]", Key("left")],
        "block": [" {}", Key("left enter enter up tab")],
        "empty array": "[]",
        "empty dict": "{}",
        "state (def | deaf | deft)": "def ",
        "state else if": "elif ",
        "state if": "if ",
        "state else if": [" else if ()", Key("left")],
        "state while": ["while ()", Key("left")],
        "state for": ["for ()", Key("left")],
        "state for": "for ",
        "state switch": ["switch ()", Key("left")],
        "state case": ["case \nbreak;", Key("up")],
        "state goto": "goto ",
        "state import": "import ",
        "state class": "class ",
        "state include": "#include ",
        "state include system": ["#include <>", Key("left")],
        "state include local": ['#include ""', Key("left")],
        "state type deaf": "typedef ",
        "state type deaf struct": ["typedef struct {\n\n};", Key("up"), "\t"],
        "comment see": "// ",
        "comment py": "# ",
        "word queue": "queue",
        "word eye": "eye",
        "word bson": "bson",
        "word iter": "iter",
        "word no": "NULL",
        "word cmd": "cmd",
        "word dup": "dup",
        "word streak": ["streq()", Key("left")],
        "word printf": "printf",
        "word (dickt | dictionary)": "dict",
        "word shell": "shell",
        "word talon": "talon",
        "dunder in it": "__init__",
        "self taught": "self.",
        "dickt in it": ["{}", Key("left")],
        "list in it": ["[]", Key("left")],
        "string utf8": "'utf8'",
        "state past": "pass",
        "plus": "+",
        "arrow": "->",
        "call": "()",
        "indirect": "&",
        "dereference": "*",
        "(op equals | assign | equeft)": " = ",
        "(op (minus | subtract) | deminus)": " - ",
        "(op (plus | add) | deplush)": " + ",
        "(op (times | multiply) | duster)": " * ",
        "(op divide | divy)": " / ",
        "op mod": " % ",
        "[op] (minus | subtract) equals": " -= ",
        "[op] (plus | add) equals": " += ",
        "[op] (times | multiply) equals": " *= ",
        "[op] divide equals": " /= ",
        "[op] mod equals": " %= ",
        "(op | is) greater [than]": " > ",
        "(op | is) less [than]": " < ",
        "(op | is) equal": " == ",
        "(op | is) not equal": " != ",
        "(op | is) greater [than] or equal": " >= ",
        "(op | is) less [than] or equal": " <= ",
        "(op (power | exponent) | to the power [of])": " ** ",
        "op and": " && ",
        "op or": " || ",
        "[op] (logical | bitwise) and": " & ",
        "[op] (logical | bitwise) or": " | ",
        "(op | logical | bitwise) (ex | exclusive) or": " ^ ",
        "[(op | logical | bitwise)] (left shift | shift left)": " << ",
        "[(op | logical | bitwise)] (right shift | shift right)": " >> ",
        "(op | logical | bitwise) and equals": " &= ",
        "(op | logical | bitwise) or equals": " |= ",
        "(op | logical | bitwise) (ex | exclusive) or equals": " ^= ",
        "[(op | logical | bitwise)] (left shift | shift left) equals": " <<= ",
        "[(op | logical | bitwise)] (right shift | shift right) equals": " >>= ",
        "shebang bash": "#!/bin/bash -u\n",
        "new window": Key("cmd-n"),
        "next window": Key("cmd-`"),
        "last window": Key("cmd-shift-`"),
        "next app": Key("cmd-tab"),
        "last app": Key("cmd-shift-tab"),
        "next tab": Key("cmd-shift-]"),
        "new tab": Key("cmd-t"),
        "(last | prevous | preev) tab": Key("cmd-shift-["),
        "next space": Key("cmd-alt-ctrl-right"),
        "last space": Key("cmd-alt-ctrl-left"),
        "scroll down": [Key("down")] * 30,
        "scroll up": [Key("up")] * 30,
        "(marco | search)": Key("cmd-f"),
        "marneck": Key("cmd-g"),
        "marpreev": Key("cmd-shift-g"),
        "marthis": [
            Key("alt-right"),
            Key("shift-alt-left"),
            Key("cmd-f"),
            Key("enter"),
        ],
        "launcher": Key("cmd-space"),
        "prefies": Key("cmd-,"),
        "put computer to sleep": lambda m: os.system("pmset sleepnow"),
    }
)
