from talon.voice import Context, Str

# from ..utils import alternatives

ctx = Context("shrink")


def shrink_word(m):
    # Str(shrink_map[" ".join(m["shrink.words"])])(None)
    Str(shrink_map[m[1]])(None)


shrink_map = {
    "administrator": "admin",
    "alternate": "alt",
    "apartment": "apt",
    "application": "app",
    "applications": "apps",
    "argument": "arg",
    "arguments": "args",
    "attribute": "attr",
    "attributes": "attrs",
    "authentication": "auth",
    "button": "btn",
    "command": "cmd",
    "compute": "cmp",
    "context": "ctx",
    "concatenate": "concat",
    "configure": "config",
    "control": "ctrl",
    "format": "fmt",
    "image": "img",
    "jason": "json",
    "message": "msg",
    "package": "pkg",
    "parameter": "param",
    "source": "src",
    "standard": "std",
    "temporary": "tmp",
    "text": "txt",
    "user": "usr",
    "user id": "uid",
    "utilities": "utils",
    "user": "usr",
    "error": "err",
    "boolean": "bool",
    "return": "ret",
    "package": "pkg",
    "python": "py",
    "project": "proj",
    "random": "rand",
    "frequency": "freq",
    "operations": "ops",
    "initialize": "init",
    "iterator": "iter",
    "vector": "vec",
    "convolution": "conv",
    "deconvolution": "deconv",
    "derivative": "deriv",
    "destination": "dest",
    "distribution": "dist",
    "contribute": "contrib",
    "delete": "del",
    "different": "diff",
    "square root": "sqrt",
    "sequence": "seq",
    "predict": "pred",
    "ending": "end",
    "yaml": "yml",
    "condition": "cond",
    "validation": "val",
    "optimization": "opt",
    "generator": "gen",
    "memory": "mem",
    "environments": "envs",
    "environment": "env",
    "application": "app",
    "inc.": "inc",
    "include": "inc",
    "_c": "char",
    "administrator": "admin",
    "administrators": "admins",
    "allocate": "alloc",
    "alternate": "alt",
    "apartment": "apt",
    "application": "app",
    "applications": "apps",
    "architecture": "arch",
    "argument": "arg",
    "arguments": "args",
    "attribute": "attr",
    "attributes": "attrs",
    "authentic": "auth",
    "authenticate": "auth",
    "author": "auth",
    "binary": "bin",
    "button": "btn",
    "calculate": "calc",
    "call": "col",
    "car": "char",
    "care": "char",
    "certificate": "cert",
    "character": "char",
    "column": "col",
    "command": "cmd",
    "concatenate": "concat",
    "configuration": "config",
    "configure": "config",
    "constant": "const",
    "define": "def",
    "descending": "desc",
    "develop": "dev",
    "developer": "dev",
    "development": "dev",
    "dictionary": "dict",
    "directory": "dir",
    "divider": "div",
    "document": "doc",
    "environment": "env",
    "execute": "exec",
    "extend": "ext",
    "extension": "ext",
    "favorite": "fav",
    "function": "func",
    "image": "img",
    "imager": "int",
    "incorporate": "inc",
    "increment": "inc",
    "initialize": "init",
    "integer": "int",
    "iterate": "iter",
    "jason": "json",
    "language": "lang",
    "large": "lg",
    "latitude": "lat",
    "length": "len",
    "library": "lib",
    "locate": "loc",
    "location": "loc",
    "longitude": "lng",
    "medium": "md",
    "minimum": "min",
    "miscellaneous": "misc",
    "navigate": "nav",
    "navigation": "nav",
    "number": "num",
    "object": "obj",
    "parameter": "param",
    "parameters": "params",
    "position": "pos",
    "previous": "prev",
    "production": "prod",
    "pseudo": "sudo",
    "rectangle": "rect",
    "reference": "ref",
    "references": "refs",
    "repeat": "rep",
    "request": "req",
    "result": "res",
    "revision": "rev",
    "session": "sess",
    "source": "src",
    "standard": "std",
    "standing": "stdin",
    "standout": "stdout",
    "string": "str",
    "synchronize": "sync",
    "synthesizer": "synth",
    "system": "sys",
    "temporary": "tmp",
    "text": "txt",
    "thanks": "thx",
    "utilities": "utils",
    "utility": "util",
    "value": "val",
    "variable": "var",
    "velocity": "vel",
    # months,
    "january": "jan",
    "february": "feb",
    "march": "mar",
    "april": "apr",
    "june": "jun",
    "july": "jul",
    "august": "aug",
    "september": "sept",
    "october": "oct",
    "november": "nov",
    "december": "dec",
}


def alternatives(options):
    return " (" + " | ".join(sorted(map(str, options))) + ")"


ctx.keymap({"shrink" + alternatives(shrink_map.keys()): shrink_word})
# ctx.keymap({"shrink {shrink.words}": shrink_word})
# ctx.set_list("words", shrink_map.keys())
